use_frameworks!

install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true

platform :ios, '8.0'

target 'KLServer_Example' do
  pod 'KLServer', :path => '../'

  target 'KLServer_Tests' do
    inherit! :search_paths

    
  end
end
